### Create Reports 
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 2013,
    "mileage": 250000,
    "price": 5000,
    "lat": 39.713650,
    "lng": -82.599281
}

### Approve Report
PATCH http://localhost:3000/reports/6
content-type: application/json

{
    "approved": true
}

### Get an estimate for a car

GET http://localhost:3000/reports?make=Toyota&model=Corolla&year=2012&mileage=100000&lat=39.713650&lng=-82.599281