### Create New User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test136@test.com",
  "password": "test123"
}

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test136@test.com",
  "password": "test123"
}

### Find a particular user by id

GET http://localhost:3000/auth/1


### Find all by email 
GET http://localhost:3000/auth?email=mtrew2016@gmail.com


### Update User
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "mtrew2016@gmail.com" 
}

### Delete User
DELETE http://localhost:3000/auth/6

### Sign In 

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test136@test.com",
  "password": "test123"
}

### Set Color
GET http://localhost:3000/auth/colors/red

### Get Color

GET http://localhost:3000/auth/colors

### whoAmI 

GET http://localhost:3000/auth/whoami


### Sign Out

POST http://localhost:3000/auth/signout
